export const departments = [
  "Management",
  "Procuration",
  "HR",
  "Marketing",
  "Finance",
  "IT",
  "Technical Support",
  "Sales",
  "Customer care",
  "Administration",
  "Research",
  "Purchase",
  "Production",
];
