export type SocialType =
  | "facebook"
  | "instagram"
  | "twitter"
  | "linkedin"
  | "pinterest"
  | "github"
  | "strava"
  | "spotify"
  | "youtube"
  | "tiktok"
  | "custom_url"
  | "video"
  | "special_offer"
  | "catalogue"
  | "whatsapp"
  | "viber"
  | "flyer";
